import React from "react";
import "tachyons";

import {
  Page,
  Text,
  View,
  Document,
  StyleSheet,
  PDFDownloadLink
} from "@react-pdf/renderer";
import { PDFViewer } from "@react-pdf/renderer";

function Reportpdf() {
  const pdfstyle = {
    width: 1000,
    height: 900
  };
  return (
    <div className="App tc ma6-ns ba4-ns">
      <div>
        <h1 className="tc">MID System Report</h1>
      </div>
      <PDFViewer className="tc pa4-ns" style={pdfstyle}>
        <Mydoc />
      </PDFViewer>
    </div>
  );
} // Create styles

/*
        this is use to display download button on report file
        <PDFDownloadLink document={<Mydoc />} fileName="sample.pdf">
          {({ bolb, url, loading, error }) =>
            loading ? "Loading Document...." : "Download Now!"
          }
        </PDFDownloadLink>
*/
const styles = StyleSheet.create({
  page: { backgroundColor: "tomato" },

  section: {
    color: "white",
    textAlign: "center",
    margin: 30,
    width: 200,
    "@media max-width: 400": {
      width: 300
    },
    "@media orientation: landscape": {
      width: 400
    }
  }
});

// Create Document Component
const Mydoc = () => (
  <Document>
    <Page size="A4">
      <View className="section">
        <Text>Medical Imaging Diagonistic System Report</Text>
      </View>
      <View className="section">
        <Text>This is a sample report that is generated by MID</Text>
      </View>
      <View className="section">
        <Text>
          This will produce a PDF document with a single page. Inside, two
          different blocks, each of them rendering a different text. These are
          not the only valid primitives you can use. Please refer to the
          Components or Examples sections for more information.
        </Text>
      </View>
      <View className="section">
        <Text>
          This will produce a PDF document with a single page. Inside, two
          different blocks, each of them rendering a different text. These are
          not the only valid primitives you can use. Please refer to the
          Components or Examples sections for more information.
        </Text>
      </View>
      <View className="section">
        <Text>
          This will produce a PDF document with a single page. Inside, two
          different blocks, each of them rendering a different text. These are
          not the only valid primitives you can use. Please refer to the
          Components or Examples sections for more information.
        </Text>
      </View>
      <View className="section">
        <Text>
          This will produce a PDF document with a single page. Inside, two
          different blocks, each of them rendering a different text. These are
          not the only valid primitives you can use. Please refer to the
          Components or Examples sections for more information.
        </Text>
      </View>
      <View className="section">
        <Text>
          This will produce a PDF document with a single page. Inside, two
          different blocks, each of them rendering a different text. These are
          not the only valid primitives you can use. Please refer to the
          Components or Examples sections for more information.
        </Text>
      </View>
    </Page>
  </Document>
);
export default Reportpdf;
